name: 'Terraformer container actions'
description: 'Terraform action demonstrations'
author: 'nereydacastro'
inputs:
  ARM_CLIENT_ID:
    description: 'Azure client id'
    required: true
  ARM_CLIENT_SECRET:
    description: 'Azure client secret'
    required: true
  ARM_SUBSCRIPTION_ID:
    description: 'Azure subrition ID'
    required: true
  ARM_TENANT_ID:
    description: 'Azure tenant ID'
    required: true
  STATE_KEY:
    description: 'Personal identification'
    required: true
  TF_STAGE:
    description: 'Django secret key to start'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
